### ISSUE TITLE
Projet sérieux

### ISSUE THREAD

**Issue by Cluniat** [PolytechLyon/git-5a-g1-gui_lefebvre#11]

**Comment by guilfb** [comment]
C'est moiiiiiiii

**Comment by Cluniat** [comment]
Dans ce cas occupe toi du dossier

**Comment by guilfb** [comment]
Mmmmmmok

**Comment by Cluniat** [comment]
J'ai du résoudre des conflits à cause de toi c'est pas cool. Tu es méchant donc tu travailles

**Comment by guilfb** [comment]
J'ai fait mes remerciements et le dossier

Voilaaaaaaaaaaaaa

PS : Je croyais c'était moi qui avait résolu le conflit mdr

**Comment by Cluniat** [comment]
Mais t'aurais du mettre le fichier qu'on a tous modifié dans le dossier

**Comment by Cluniat** [comment]
T'es vraiment super méchant en fait.

**Comment by guilfb** [comment]
Il a pas dit qu'il voulait un remerciement par personne ?

**Comment by guilfb** [comment]
Dans un fichier à part ?

**Comment by Cluniat** [comment]
Tout dans le meme fichier

**Comment by tobany** [comment]
Ouais il ne faut pas un fichier par personne, mais juste que tous le monde participe

**Comment by guilfb** [comment]
Oupssssssssssss

**Comment by guilfb** [comment]
Désoléééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééééé

**Comment by guilfb** [comment]
Trql plus qu'à push sur mon fichier les gars

**Comment by guilfb** [comment]
JAI ECRIT DIRECT DANS LE MASTER ET JAVAIS PUSH

JEN SUIS SUR
