### ISSUE TITLE
C'est hugo qui crée le fichier du coup ? 

### ISSUE THREAD

**Issue by Cluniat** [PolytechLyon/git-5a-g1-gui_lefebvre#2]

**Comment by guilfb** [comment]
Oui normalement il se charge de tout, on ajoute ensuite notre texte chacun notre tour

**Comment by guilfb** [comment]
Ca repond a ta requete ?

**Comment by Cluniat** [comment]
Sinon il crée, on fait chacun une branche avec notre bout de texte puis on merge tout dans l'ordre

**Comment by guilfb** [comment]
Boboboboooo c'est technique

**Comment by Cluniat** [comment]
Bonjour Guillaume ceci est un cours sur Git

**Comment by hugobatton** [comment]
Je l'ai crée

**Comment by Cluniat** [comment]
Merci bien ! Du coup, branche puis PR ? on est d'accord Guillaume ?

**Comment by guilfb** [comment]
Je vois plus ton msg Philippine

**Comment by guilfb** [comment]
Hugo t'as écrit ?

**Comment by guilfb** [comment]
Oui oui tqt :)

**Comment by hugobatton** [comment]
Yes une intro futuriste

**Comment by hugobatton** [comment]
La meme que quand je suis passé dans faites entrer l'accusé
