### ISSUE TITLE
Que faites vous ? 

### ISSUE THREAD

**Issue by Cluniat** [PolytechLyon/git-5a-g1-gui_lefebvre#4]

**Comment by guilfb** [comment]
J'étais en pleine narration sorry

**Comment by Cluniat** [comment]
C'est les deux phrases les plus longues du monde

**Comment by guilfb** [comment]
Elles sont magnifiques

**Comment by guilfb** [comment]
Je trouve ça un peu simpliste d'ailleurs ce que tu as produit

**Comment by Cluniat** [comment]
Oui tu es le meilleur guillaume bravo. Tu peux pousser ta petite branche maintenant stp ?

**Comment by guilfb** [comment]
Mdrr c'est fait je crois

**Comment by guilfb** [comment]
Tu vois pas la branche Gui ? normalement elle est push

**Comment by Cluniat** [comment]
Guillaume fallait pas supprimé le truc d'Hugo

**Comment by guilfb** [comment]
trql je le remets
ca va aller vite

**Comment by Cluniat** [comment]
Faut écrire à la suite parce que maintenant quand tu merge ca vire le truc d'Hugo ... 
Merci bien

**Comment by guilfb** [comment]
C'est fait

**Comment by hugobatton** [comment]
Qui crée la 4ème de couverture du coup
