### ISSUE TITLE
Qui s'occupe de la 4eme de couverture ? 

### ISSUE THREAD

**Issue by Cluniat** [PolytechLyon/git-5a-g1-gui_lefebvre#5]

**Comment by guilfb** [comment]
Ca se voit tu maitrises git t'es trop vive

j'ai ce lien d'image si ca vous va

**Comment by guilfb** [comment]
https://images-na.ssl-images-amazon.com/images/I/519zq%2BCSuJL._SX367_BO1,204,203,200_.jpg

**Comment by hugobatton** [comment]
C'est parfait

**Comment by tobany** [comment]
Par contre ça c'est une première de couverture

**Comment by guilfb** [comment]
Oups mdrr c'est pas grave elle est belle l'image

**Comment by hugobatton** [comment]
Je pense qu'on aura une première de couv après à mettre..

**Comment by hugobatton** [comment]
Par contre tout n'est pas merge sur la master la si ?

**Comment by guilfb** [comment]
Nan et y'a un souci d'accents askip

**Comment by Cluniat** [comment]
Faies une branche "premiere-couv" et une "deuxieme-couv" comme ça on anticipe et tout t'as vu

**Comment by Cluniat** [comment]
J'ai tout merge oui

**Comment by tobany** [comment]
Et du coup comme 4eme de couverture, on fait juste un résumé ou on essaie de faire plus ?

**Comment by guilfb** [comment]
Mais 4eme de couverture c'est juste l'image de l'arrière du livre nan ?

**Comment by Cluniat** [comment]
Y a pas d'image à l'arrière des livres... c'est le résumé du livre derrière ...

**Comment by guilfb** [comment]
Ou bien il croit on va faire un montage genre on crée un texte qu'on ajoute sur l'image

**Comment by hugobatton** [comment]
C'est pas une image c'est un résumé

**Comment by Cluniat** [comment]
Bref je fais la 4eme couverture si vous voulez

**Comment by guilfb** [comment]
Y'a aussi des images souvent... :'(

**Comment by guilfb** [comment]
Ca marche, U tu crées le fichier de remerciements ?

**Comment by tobany** [comment]
juste un résumé c'est bien

**Comment by hugobatton** [comment]
Avec plaisir

**Comment by hugobatton** [comment]
done

**Comment by guilfb** [comment]
Vous voulez on refasse l'histoire des merges avec les branches ? ou chacun écrit à la suite sur le fichier dans la branche master ?

**Comment by hugobatton** [comment]
C'est moins propre de pas faire de branche mais c'est plus rapide aussi mdrr

**Comment by guilfb** [comment]
Go sans branches alors

**Comment by guilfb** [comment]
A mon tour d'ecrire
